### ISSUE TITLE
Missing Dep. at on setup.php

### ISSUE THREAD

**Issue by lan1hotspots** [jtylek/Epesi#8]
I tried a freash installation and got these error 

Warning: require_once(modules/Libs/QuickForm/requires.php): failed to open stream: No such file or directory in /var/www/setup.php on line 20

Fatal error: require_once(): Failed opening required 'modules/Libs/QuickForm/requires.php' (include_path='.:/usr/local/lib/php') in /var/www/setup.php on line 20

**Comment by jtylek** [comment]
I am in the process of rewriting QuickForm to be compatible with PHP 7.1
Until now please use the package from SourceForge: https://sourceforge.net/projects/epesi/
